### PR TITLE
Customize prefix in actions type

### PR DESCRIPTION
**Pull request by Means88**
The reducers name usually conflicted in a big project, or we want to use the same API in different cases (have different status at the same time).It's difficult to ensure the differences of reducers name in the whole project. I thought about put them in different `ReduxApi` using `combineReducers`, but still conflicted due to the same action type. Maybe it is one of the solutions?

### CODE REVIEW

**Comment by lexich** [comment]
But your PR fix only events names, and i think they are not conflicted. But I understand problem with reducers.

**Comment by Means88** [comment]
The problem I met is like this. I hope I didn't misunderstand how it works actually.
```js
aApi = ReduxApi({ 
  test: { ... },
  ...others
});
aReducer = combineReducers(aApi.reducers);
aAction = aApi.actions

bApi = ReduxApi({ 
  test: { ... },
  ...others 
});
bReducer = combineReducers(bApi.reducers);
bAction = bApi.actions

reducer = combineReducers({
  a: aReducer, 
  b: bReducer
});

store = createStore(reducer);

// It will update state.b too, right?
// because they have the same action type
store.dispatch(aAction.test());
```

**Comment by lexich** [comment]
Oh thank you for interesting example. I didn't know that it's posible to use combineReducers "nested".
I apply you PR with some modification.
The better way is
```js
export default function reduxApi(config, { customPrefix }) {
```
Second args should be Object for more flexibility.

**Comment by Means88** [comment]
OK, I've updated my PR, and, thanks for your fantastic library, it helps me a lot.

**Comment by lexich** [comment]
@Means88 you can update to new version

**Pull request merged**
