### PR TITLE
Add qsParseOptions and qsStringifyOptions options

### PR DESCRIPTION
**Pull request by wvengen**
implements #85 

Open questions
- [x] Why does eslint complain about line-length, when other tests in `urlTransform_spec` are longer?

### CODE REVIEW

**Comment by wvengen** [comment]
Would default options be solved in a proper way by moving the `globalOptions` / `baseOptions` / `opts` merging block up in `actionFn`'s `request` function and using that?

**Comment by wvengen** [comment]
Hmm this is a bit tricky: in `actionFn`'s `request` function, the merged options depend on the url. Now this changes makes the url dependent on the options. How to solve this, any ideas?

**Comment by lexich** [comment]
I think that first of all we need additional option for definition endpoint.
```js
reduxApi({
   test: {
     url: "/test",
     urlOptions: { .... }
   }
});
```
Access to this option is through `meta` in [`actionFn`](https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L52)

The main problem that you [merge](https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L80-L81) HTTP request options with `urlOptions`.
Solution, as I think, you need to pick `urlOptions` from `params` in [`request`](https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L62) function

**Comment by wvengen** [comment]
Ah, that indeed sounds better. Thanks!

**Comment by wvengen** [comment]
Is this approach better?

**Comment by lexich** [comment]
Great work @wvengen I need extra time to analyse code, but at first sight it looks good 👍

**Comment by wvengen** [comment]
Thanks for the early feedback :)

**Comment by lexich** [comment]
I thought that you finished otherwise you way is true

**Comment by wvengen** [comment]
Yes, somehow I missed this, sorry!

**Comment by lexich** [comment]
@wvengen  Thx for your work, i merged your PR with some fixes. If you have some new ideas about current (or new) functionality - you are welcome 👍

**Comment by wvengen** [comment]
Thank you!!

**Pull request merged**
