### PR TITLE
Crud option

### PR DESCRIPTION
**Pull request by lexich**

### CODE REVIEW

**Comment by hashwin** [comment]
That was really quick! I'll test it out soon and get back to you.

**Comment by hashwin** [comment]
This is awesome, it works as expected! :+1: 

Just a couple of more requests from my side since we are using a Rails backend:
1. Rails uses PATCH for updates, so if we could have an additional .patch() method, that would amazing.
2. Rails accepts wrapped parameters with the resource name, i.e. for user, the params that would be sent would be something like:
```
{
  user: {
    name: 'abc'
    age: 24
  }
}
```
Would be nice to have that option.

3. Other than the GET request, the params should probably go into the body of the request. Right now I am seeing the params are part of the URL itself.

**Comment by lexich** [comment]
@hashwin 
1. OK
2. I don't think that it's good idea, because redux-api is backend independent library.
3. For this situation you should write you own helper, I think that crud api shouldn't be very complex.

Otherwise, If you write some code, with examples of convenient syntax, maybe I make it implementaion.

**Comment by hashwin** [comment]
Yeah, the wrapper thing was only a nice to have - don't worry about that one.

But for the 3rd point, I think that passing url params actually limits the amount of data you can send because URL lengths have a limit (See http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).  But you can send body data of any size.

**Comment by lexich** [comment]
Get request hasn't body. And main idea of redux-api is generate actions and reducers for rest calls, without hard linking to any technology. (you can use fetch, $.ajax or browser syntax in browser and also you can use it on server side). And I think that hard binding to `fetch` isn't good idea, but analyse request's params is way to this lock.

**Comment by hashwin** [comment]
I meant for requests other than GET.

Anyway, this is very helpful, thank you.

**Comment by lexich** [comment]
You are welcome :)

**Pull request merged**
